### ISSUE TITLE
Still can't choose??!!

### ISSUE THREAD

**Issue by alexytsu** [ashalexis/lets-choose#1]
Please help, as I'm fast losing all my hair over not being able to decide what to eat. I thought this might help me choose but I'm STILL stumped. 

### Issue
No specific dish was selected. 

### Steps to reproduce
Partner A eliminates Chinese
Partner B eliminates Indian
Partner A eliminates Japanese
Partner B eliminates Korean
Partner A eliminates Malaysian
Partner B eliminates Thai
Partner A eliminates Vietnamese
Partner B eliminates Filipino
Partner A eliminates Lebanese
Partner B eliminates Italian
Partner A eliminates French
Partner B eliminates Spanish
Partner A eliminates Mexican
Partner B eliminates Greek
Partner A eliminates Australian
Partner B eliminates American
Partner A eliminates Cajun

### Output
Hungarian

### Expected behaviour
No loss of hair

### Actual behaviour
Loss of hair has been accelerated. Please help, my Hungarian _nem túl jó_ and I can't find any good restaurants in my area. Furthermore, I am still paralysed by choice as if (in the unlikely event) I actually made it to a Hungarian restuarant I would still be unable to choose a dish. 

Please do you have a recommendation:
- Gulyás??
- Halászlé
- ??
- Csirke Paprikás??
- Hortobagyi Palacsinta
- Töltött Káposzta mmmaybe?
- Pörkölt (classic)
- Meggyleves
- Túrós Csusza

**Comment by ashalexis** [comment]
Unfortunately I did not think of this absolute madness of a dilemma for the MVP - this will be taken into consideration in the future. Hooking up to a map is also a todo on my list, so worry not!

P.S.
Personally I would suggest a Gulyás (can't go wrong), Lángos (fried is forever), or Túrós Csusza (traditional and yummy!). I wish you the best in your quest for sustenance.
